---
title: "SQL"
output: html_document
date: "2024-11-12"
---

```{r}
install.packages("DBI")
install.packages("RSQLite")
install.packages("dbplyr")

library(DBI)
library(RSQLite)
library(dbplyr)
library(here)
```

In SQL databases, the data itself is not stored in a particular order but we can control that.

* is an operator that means "all" like all columns

DISTINCT can apply for 2 columns

WHERE variable = "character_string" <-- character string goes in quotes

```{r}
connection <- dbConnect(drv = RSQLite::SQLite(), 
                        dbname = here::here("survey.db"))
results <- dbGetQuery(connection, "SELECT * FROM Person ORDER BY id DESC;")
print(results)
```

IN-CLASS ACTIVITY

Part 1

```{r}
songs <- data.frame(
  song_id = 1:10,
  title = c("Crazy in Love", "Halo", "Single Ladies", "Formation", "Irreplaceable", 
            "Drunk in Love", "Run the World", "Partition", "Love on Top", "Sorry"),
  album_id = c(1, 2, 1, 3, 2, 3, 1, 3, 2, 3),
  release_year = c(2003, 2008, 2008, 2016, 2006, 2013, 2011, 2013, 2011, 2016),
  streams_millions = c(500, 600, 700, 800, 900, 1000, 450, 350, 750, 900)
)

# Sample data frame for Beyoncé's albums
albums <- data.frame(
  album_id = 1:3,
  album_title = c("Dangerously in Love", "I Am... Sasha Fierce", "Lemonade"),
  release_year = c(2003, 2008, 2016)
)
```

```{r}
sql_beyonce <- here::here("beyonce.sqlite")
mydb <- dbConnect(SQLite(), sql_beyonce)

dbWriteTable(mydb, "songs", songs, row.names = FALSE)
dbWriteTable(mydb, "albums", albums, row.names = FALSE)
dbListTables(mydb)
```

Part 2  

```{r}
songs

dbGetQuery(mydb, "SELECT * FROM Songs WHERE streams_millions > 600;")

dbGetQuery(mydb, "SELECT title, release_year FROM Songs WHERE release_year > 2010")

albums
songs

dbGetQuery(mydb, "SELECT album_id, COUNT(song_id) AS song_count FROM songs GROUP BY album_id;")

dbGetQuery(mydb, "SELECT album_id, title, SUM(streams_millions) AS stream_count FROM songs GROUP BY album_id;")
           
dbGetQuery(mydb, "SELECT release_year, title, MIN(streams_millions) AS least_streams 
           FROM songs 
           GROUP BY release_year;")

songs
```

